import type {
  Composition,
  Event,
  PianoRollNote,
  Provenance,
  ProvenanceSource,
  RuleDefinition,
  VoiceDef,
} from '@/types/aurora';
import {
  beatToFloat,
  durationToBeats,
  eventBase,
  eventId,
  midiToName,
} from '@/types/aurora';

export interface DrumMapRow {
  midi: number;
  name: string;
  shortName: string;
}

export const DRUM_MAP: DrumMapRow[] = [
  { midi: 36, name: 'Bass Drum', shortName: 'BD' },
  { midi: 38, name: 'Snare', shortName: 'SN' },
  { midi: 42, name: 'Closed Hi-Hat', shortName: 'HH' },
  { midi: 46, name: 'Open Hi-Hat', shortName: 'OH' },
  { midi: 49, name: 'Crash', shortName: 'CR' },
  { midi: 51, name: 'Ride', shortName: 'RD' },
];

export function isDrumVoice(voice: VoiceDef): boolean {
  return /drum|percussion|kit/i.test(voice.name);
}

export function drumLabel(midi: number): string {
  return DRUM_MAP.find((r) => r.midi === midi)?.shortName ?? String(midi);
}

function formatSummary(prov: Provenance, rules: RuleDefinition[]): string {
  const ruleLabel =
    rules[0]?.display_id ??
    (prov.stage ? `${String(prov.stage)} Engine` : sourceLabel(prov.source));
  const score =
    prov.eval_score != null ? `${prov.eval_score >= 0 ? '+' : ''}${Math.round(prov.eval_score)}` : '—';
  const reason = prov.explanation ?? 'No explanation';
  return `Generated by: ${ruleLabel}, Score: ${score}, Reason: ${reason}`;
}

function sourceLabel(source: ProvenanceSource): string {
  switch (source) {
    case 'ManualEdit':
      return 'Manual Edit';
    case 'Imported':
      return 'Import';
    case 'Repaired':
      return 'Repair Engine';
    case 'Plugin':
      return 'Plugin';
    case 'Transformed':
      return 'Transform';
    default:
      return 'Unknown Rule';
  }
}

function rulesFromProvenance(prov: Provenance): RuleDefinition[] {
  return prov.rule_refs.map((r) => {
    const category = r.id.split('.')[0] ?? 'rule';
    const name = (r.id.split('.')[1] ?? r.id).replace(/_/g, ' ');
    const displayNum = (r.id.length % 100) + 1;
    return {
      id: r.id,
      display_id: `${capitalize(category)} Rule #${displayNum}`,
      name: capitalize(name),
      category,
      description: '',
      weight: r.weight ?? 1,
      contribution_score: r.score,
    };
  });
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function extractPianoRollNotes(comp: Composition, voiceId?: number): PianoRollNote[] {
  const notes: PianoRollNote[] = [];
  const voiceMap = new Map(comp.voice_registry.voices.map((v) => [v.id, v.name]));

  for (const movement of comp.movements) {
    for (const section of movement.sections) {
      for (const phrase of section.phrases) {
        for (const measure of phrase.measures) {
          for (const mv of measure.voices) {
            if (voiceId != null && mv.voice_id !== voiceId) continue;
            const voiceName = voiceMap.get(mv.voice_id) ?? `Voice ${mv.voice_id}`;
            for (const event of mv.events) {
              const note = eventToPianoRollNote(
                event,
                mv.voice_id,
                voiceName,
                measure.number.global,
              );
              if (note) notes.push(note);
            }
          }
        }
      }
    }
  }
  return notes;
}

function eventToPianoRollNote(
  event: Event,
  voiceId: number,
  voiceName: string,
  measureGlobal: number,
): PianoRollNote | null {
  if (event.kind !== 'Note') return null;
  const base = eventBase(event);
  const rules = rulesFromProvenance(base.provenance);
  return {
    nodeId: eventId(event),
    voiceId,
    voiceName,
    pitchMidi: event.pitch.midi,
    startMeasure: measureGlobal,
    startBeat: base.offset,
    durationBeats: durationToBeats(base.duration),
    velocity: event.velocity,
    pitchRole: event.pitch_role,
    provenanceSource: base.provenance.source,
    provenanceSummary: formatSummary(base.provenance, rules),
  };
}

export function drumMidiToRowIndex(midi: number): number {
  const idx = DRUM_MAP.findIndex((r) => r.midi === midi);
  if (idx >= 0) return idx;
  // Unmapped percussion: one row per MIDI pitch (avoid collapsing to row 0).
  return DRUM_MAP.length + (midi % 24);
}

export function drumRowCountForNotes(notes: PianoRollNote[]): number {
  let maxRow = DRUM_MAP.length;
  for (const n of notes) {
    maxRow = Math.max(maxRow, drumMidiToRowIndex(n.pitchMidi) + 1);
  }
  return Math.max(DRUM_MAP.length, maxRow);
}

export function rowIndexToDrumMidi(rowIndex: number): number {
  if (rowIndex >= 0 && rowIndex < DRUM_MAP.length) {
    return DRUM_MAP[rowIndex]?.midi ?? 36;
  }
  return 36 + (rowIndex - DRUM_MAP.length);
}

export function drumRowToY(rowIndex: number, rowHeight: number): number {
  return rowIndex * rowHeight;
}

export function yToDrumRowIndex(y: number, rowHeight: number, maxRows?: number): number {
  const idx = Math.max(0, Math.round(y / rowHeight));
  if (maxRows != null) return Math.min(maxRows - 1, idx);
  return idx;
}

export function measureToX(measure: number, zoom: number, scrollX: number): number {
  return (measure - 1) * zoom - scrollX;
}

export function xToMeasure(x: number, zoom: number, scrollX: number): number {
  return Math.floor((x + scrollX) / zoom) + 1;
}

export function beatToX(
  measure: number,
  beat: number,
  beatsPerMeasure: number,
  zoom: number,
  scrollX: number,
): number {
  const measureStart = measureToX(measure, zoom, scrollX);
  return measureStart + (beat / beatsPerMeasure) * zoom;
}

export function noteX(
  note: PianoRollNote,
  beatsPerMeasure: number,
  zoom: number,
  scrollX: number,
): number {
  return beatToX(
    note.startMeasure,
    beatToFloat(note.startBeat),
    beatsPerMeasure,
    zoom,
    scrollX,
  );
}

export function noteWidth(note: PianoRollNote, beatsPerMeasure: number, zoom: number): number {
  return (note.durationBeats / beatsPerMeasure) * zoom;
}

export function pitchToY(midi: number, _minMidi: number, maxMidi: number, rowHeight: number): number {
  return (maxMidi - midi) * rowHeight;
}

const BLACK_KEY_PCS = new Set([1, 3, 6, 8, 10]);

export function isBlackKey(midi: number): boolean {
  return BLACK_KEY_PCS.has(midi % 12);
}

export function visiblePitchRange(notes: PianoRollNote[], paddingSemitones = 6): [number, number] {
  if (notes.length === 0) return [48, 84];
  let min = 127;
  let max = 0;
  for (const n of notes) {
    min = Math.min(min, n.pitchMidi);
    max = Math.max(max, n.pitchMidi);
  }
  min -= paddingSemitones;
  max += paddingSemitones;
  const minOct = Math.floor(min / 12) * 12;
  const maxOct = Math.min(127, Math.ceil((max + 1) / 12) * 12 - 1);
  return [Math.max(0, minOct), Math.max(minOct, maxOct)];
}

export function pitchLabel(midi: number): string {
  return midiToName(midi);
}

export function drumRowLabel(midi: number): string {
  const row = DRUM_MAP.find((r) => r.midi === midi);
  if (row) return row.shortName;
  return midiToName(midi);
}

export function totalMeasuresFromNotes(notes: PianoRollNote[], fallback = 8): number {
  if (notes.length === 0) return fallback;
  return Math.max(fallback, ...notes.map((n) => n.startMeasure));
}

export function globalBeatToPosition(
  globalBeat: number,
  beatsPerMeasure: number,
): { measure: number; beat: number } {
  const measure = Math.floor(globalBeat / beatsPerMeasure) + 1;
  const beat = globalBeat % beatsPerMeasure;
  return { measure, beat };
}

export function globalBeatToX(
  globalBeat: number,
  beatsPerMeasure: number,
  zoom: number,
  scrollX: number,
  keyWidth = 0,
): number {
  const { measure, beat } = globalBeatToPosition(globalBeat, beatsPerMeasure);
  return beatToX(measure, beat, beatsPerMeasure, zoom, scrollX) + keyWidth;
}

export function xToGlobalBeat(
  x: number,
  keyWidth: number,
  beatsPerMeasure: number,
  zoom: number,
  scrollX: number,
  totalGlobalBeats: number,
): number {
  const gridX = Math.max(0, x - keyWidth);
  const measure = xToMeasure(gridX, zoom, scrollX);
  const measureStartX = measureToX(measure, zoom, scrollX);
  const beatInMeasure = ((gridX - measureStartX) / zoom) * beatsPerMeasure;
  const global = (measure - 1) * beatsPerMeasure + beatInMeasure;
  return Math.max(0, Math.min(totalGlobalBeats, global));
}
