<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { getEventProvenance, getProvenanceChain } from '@/services/tauri';
import type { ProvenanceChain, ProvenanceChainEntry } from '@/types/aurora';
import { useSelectionStore } from '@/stores/selection';
import { formatFixed } from '@/utils/format';
import { useI18n } from '@/composables/useI18n';

const { t } = useI18n();
const selection = useSelectionStore();
const chain = ref<ProvenanceChain | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const expandedSections = ref<Set<string>>(new Set(['rules', 'summary']));

const primaryEntry = computed((): ProvenanceChainEntry | null => chain.value?.entries[0] ?? null);

const summaryLines = computed(() => {
  const entry = primaryEntry.value;
  if (!entry) return null;
  const rule = entry.rules[0]?.display_id ?? 'Unknown';
  const score =
    entry.provenance.eval_score != null
      ? `${entry.provenance.eval_score >= 0 ? '+' : ''}${Math.round(entry.provenance.eval_score)}`
      : '—';
  const reason = entry.provenance.explanation ?? 'No explanation';
  return { rule, score, reason, full: entry.display_summary };
});

function toggleSection(id: string) {
  const next = new Set(expandedSections.value);
  if (next.has(id)) next.delete(id);
  else next.add(id);
  expandedSections.value = next;
}

function agentLabel(entry: ProvenanceChainEntry): string {
  const agent = entry.provenance.agent;
  if (agent.type === 'Engine') return `${String(agent.stage)} Engine`;
  if (agent.type === 'Plugin') return `Plugin (${agent.plugin_id})`;
  if (agent.type === 'User') return 'Manual Edit';
  if (agent.type === 'Import') return `Imported from ${agent.format}`;
  return 'Unknown';
}

async function loadChain() {
  const id = selection.primaryEventId;
  if (!id) {
    chain.value = null;
    return;
  }
  loading.value = true;
  error.value = null;
  try {
    chain.value = await getProvenanceChain({ node_id: id });
    await getEventProvenance({ node_id: id });
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e);
    chain.value = null;
  } finally {
    loading.value = false;
  }
}

function navigateToParent(entry: ProvenanceChainEntry) {
  const parentId = entry.provenance.parent?.node_id;
  if (parentId) selection.selectEvent(parentId);
}

watch(() => selection.primaryEventId, loadChain, { immediate: true });
</script>

<template>
  <div class="inspector">
    <header class="inspector-header">
      <h2>{{ t('inspector.title') }}</h2>
    </header>

    <p v-if="!selection.primaryEventId" class="empty-state">
      {{ t('inspector.empty') }}
    </p>

    <div v-else-if="loading" class="loading">{{ t('inspector.loading') }}</div>

    <div v-else-if="error" class="error">{{ error }}</div>

    <template v-else-if="chain">
      <section class="event-header">
        <p class="event-kind">
          {{ chain.event_summary.kind }}
          <span v-if="chain.event_summary.pitch_display">
            · {{ chain.event_summary.pitch_display }}
          </span>
        </p>
        <p class="event-meta">
          {{ chain.event_summary.voice_name }} · m.{{ chain.event_summary.measure_global }}
          <span v-if="chain.event_summary.duration_display">
            · {{ chain.event_summary.duration_display }}
          </span>
        </p>
      </section>

      <section v-if="summaryLines" class="provenance-summary">
        <button class="section-toggle" @click="toggleSection('summary')">
          {{ expandedSections.has('summary') ? '▼' : '▶' }} Primary Summary
        </button>
        <div v-if="expandedSections.has('summary')" class="summary-box">
          <p>Generated by: <strong>{{ summaryLines.rule }}</strong></p>
          <p>Score: {{ summaryLines.score }}</p>
          <p>Reason: {{ summaryLines.reason }}</p>
        </div>
      </section>

      <section class="section">
        <button class="section-toggle" @click="toggleSection('rules')">
          {{ expandedSections.has('rules') ? '▼' : '▶' }}
          Rules ({{ primaryEntry?.rules.length ?? 0 }})
        </button>
        <ul v-if="expandedSections.has('rules') && primaryEntry" class="rule-list">
          <li v-for="rule in primaryEntry.rules" :key="rule.id" class="rule-card">
            <span class="rule-id">{{ rule.display_id }}</span>
            <span class="rule-name">{{ rule.name }}</span>
            <span
              class="rule-score"
              :class="{ negative: (rule.contribution_score ?? 0) < 0 }"
            >
              {{ rule.contribution_score != null ? `${rule.contribution_score >= 0 ? '+' : ''}${rule.contribution_score}` : '—' }}
            </span>
          </li>
          <li v-if="primaryEntry.rules.length === 0" class="muted">No rules recorded</li>
        </ul>
      </section>

      <section v-if="primaryEntry?.provenance.search" class="section">
        <button class="section-toggle" @click="toggleSection('search')">
          {{ expandedSections.has('search') ? '▼' : '▶' }} Search Context
        </button>
        <dl v-if="expandedSections.has('search')" class="detail-list">
          <dt>Pipeline Stage</dt>
          <dd>{{ primaryEntry.provenance.stage ?? '—' }}</dd>
          <dt>Search Step</dt>
          <dd>{{ primaryEntry.provenance.search.step_index + 1 }}</dd>
          <dt>Beam Rank</dt>
          <dd>
            {{ primaryEntry.provenance.search.beam_rank + 1 }} /
            {{ primaryEntry.provenance.search.beam_width }}
          </dd>
          <dt>Accumulated Score</dt>
          <dd>{{ formatFixed(primaryEntry.provenance.search.accumulated_score, 1, 0) }}</dd>
        </dl>
      </section>

      <section class="section">
        <button class="section-toggle" @click="toggleSection('agent')">
          {{ expandedSections.has('agent') ? '▼' : '▶' }} Agent
        </button>
        <p v-if="expandedSections.has('agent') && primaryEntry" class="detail-text">
          {{ agentLabel(primaryEntry) }}
        </p>
      </section>

      <section v-if="chain.entries.length > 1" class="section">
        <button class="section-toggle" @click="toggleSection('parent')">
          {{ expandedSections.has('parent') ? '▼' : '▶' }}
          Parent Chain ({{ chain.entries.length - 1 }})
        </button>
        <ol v-if="expandedSections.has('parent')" class="chain-list">
          <li v-for="entry in chain.entries.slice(1)" :key="entry.depth">
            <button
              v-if="entry.provenance.parent"
              class="link-btn"
              @click="navigateToParent(entry)"
            >
              Depth {{ entry.depth }}: {{ entry.display_summary }}
            </button>
            <span v-else>{{ entry.display_summary }}</span>
          </li>
        </ol>
      </section>
    </template>
  </div>
</template>

<style scoped>
.inspector {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  font-size: 0.8125rem;
}

.inspector-header h2 {
  margin: 0;
  font-size: 0.875rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
}

.empty-state,
.loading {
  color: var(--text-muted);
  padding: 1rem 0;
}

.error {
  color: var(--error);
}

.event-header {
  padding-bottom: 0.5rem;
  border-bottom: 1px solid var(--border-muted);
}

.event-kind {
  margin: 0;
  font-weight: 600;
  color: var(--text-primary);
}

.event-meta {
  margin: 0.25rem 0 0;
  color: var(--text-muted);
}

.summary-box {
  margin-top: 0.5rem;
  padding: 0.75rem;
  background: var(--bg-input);
  border: 1px solid var(--accent-soft);
  border-radius: 6px;
}

.summary-box p {
  margin: 0.25rem 0;
}

.section-toggle {
  width: 100%;
  text-align: left;
  padding: 0.35rem 0;
  background: none;
  border: none;
  color: var(--text-primary);
  cursor: pointer;
  font-size: 0.8125rem;
  font-weight: 600;
}

.section-toggle:hover {
  color: var(--accent);
}

.rule-list {
  list-style: none;
  margin: 0.5rem 0 0;
  padding: 0;
}

.rule-card {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 0.25rem 0.5rem;
  padding: 0.5rem;
  margin-bottom: 0.35rem;
  background: var(--bg-input);
  border-radius: 4px;
  border: 1px solid var(--border-muted);
}

.rule-id {
  font-weight: 600;
  color: var(--accent);
}

.rule-name {
  grid-column: 1 / -1;
  color: var(--text-muted);
  font-size: 0.75rem;
}

.rule-score {
  color: var(--success);
  font-weight: 600;
}

.rule-score.negative {
  color: var(--error);
}

.detail-list {
  margin: 0.5rem 0 0;
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 0.25rem 0.75rem;
}

.detail-list dt {
  color: var(--text-muted);
}

.detail-list dd {
  margin: 0;
  color: var(--text-primary);
}

.detail-text {
  margin: 0.5rem 0 0;
  color: var(--text-primary);
}

.chain-list {
  margin: 0.5rem 0 0;
  padding-left: 1.25rem;
  color: var(--text-muted);
}

.link-btn {
  background: none;
  border: none;
  color: var(--accent);
  cursor: pointer;
  padding: 0;
  text-align: left;
  font-size: inherit;
}

.link-btn:hover {
  text-decoration: underline;
}

.muted {
  color: var(--text-faint);
  font-style: italic;
}
</style>
